# Generated by Django 5.0.3 on 2024-05-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_name_signup_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='eduform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Schoolname', models.CharField(max_length=100)),
                ('Passoutyear1', models.IntegerField()),
                ('Score1', models.IntegerField()),
                ('Ug', models.CharField(max_length=100)),
                ('Passoutyear2', models.IntegerField()),
                ('Score2', models.IntegerField()),
                ('Pg', models.CharField(max_length=100)),
                ('Passoutyear3', models.IntegerField()),
                ('Score3', models.IntegerField()),
            ],
        ),
    ]
