# Generated by Django 5.0.3 on 2024-05-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_personform'),
    ]

    operations = [
        migrations.CreateModel(
            name='personform1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='eduform',
            new_name='eduform1',
        ),
        migrations.DeleteModel(
            name='personform',
        ),
    ]
