# Generated by Django 5.0.3 on 2024-05-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_personform1_rename_eduform_eduform1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aadharnumber', models.CharField(max_length=12)),
                ('Pannumber', models.CharField(max_length=10)),
                ('Passportnumber', models.CharField(max_length=10)),
                ('Licencenumber', models.CharField(max_length=16)),
                ('Electionid', models.CharField(max_length=16)),
            ],
        ),
        migrations.RenameField(
            model_name='personform1',
            old_name='Gender',
            new_name='gender',
        ),
    ]
