# Generated by Django 5.0.3 on 2024-05-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_numbers_rename_gender_personform1_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('answer', models.BooleanField(default=False)),
            ],
        ),
    ]
