# Generated by Django 5.0.3 on 2024-05-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_medical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='medical',
            name='text',
        ),
        migrations.AddField(
            model_name='medical',
            name='bp',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Default bp', max_length=6),
        ),
        migrations.AddField(
            model_name='medical',
            name='cholestrol',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Default cholestrol', max_length=6),
        ),
        migrations.AddField(
            model_name='medical',
            name='diabetic',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Default diabetic', max_length=6),
        ),
        migrations.AlterField(
            model_name='eduform1',
            name='Pg',
            field=models.CharField(default='Default pg', max_length=100),
        ),
        migrations.AlterField(
            model_name='eduform1',
            name='Schoolname',
            field=models.CharField(default='Default schoolname', max_length=100),
        ),
        migrations.AlterField(
            model_name='eduform1',
            name='Ug',
            field=models.CharField(default='Default ug', max_length=100),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='Aadharnumber',
            field=models.CharField(default='Default aadhaar', max_length=12),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='Electionid',
            field=models.CharField(default='Default election', max_length=16),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='Licencenumber',
            field=models.CharField(default='Default license', max_length=16),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='Pannumber',
            field=models.CharField(default='Default pan', max_length=10),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='Passportnumber',
            field=models.CharField(default='Default passport', max_length=10),
        ),
        migrations.AlterField(
            model_name='personform1',
            name='address',
            field=models.CharField(default='Default address', max_length=255),
        ),
        migrations.AlterField(
            model_name='personform1',
            name='gender',
            field=models.CharField(default='Default gender', max_length=10),
        ),
        migrations.AlterField(
            model_name='signup',
            name='Email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='signup',
            name='Full_Name',
            field=models.CharField(default='Default fullname', max_length=100),
        ),
        migrations.AlterField(
            model_name='signup',
            name='Password',
            field=models.CharField(default='Default password', max_length=100),
        ),
        migrations.AlterField(
            model_name='signup',
            name='Username',
            field=models.CharField(default='Default username', max_length=100),
        ),
    ]
