# Generated by Django 5.0.3 on 2024-05-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_medical_answer_remove_medical_text_medical_bp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='allergy',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Default allergy', max_length=6),
        ),
        migrations.AddField(
            model_name='medical',
            name='asthma',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Default asthma', max_length=6),
        ),
        migrations.AddField(
            model_name='medical',
            name='thyroid',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Default thyroid', max_length=6),
        ),
    ]
