# Generated by Django 5.0.3 on 2024-05-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_person_name1_remove_person_name2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='amount',
            new_name='amount1',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='loan',
            new_name='loan1',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='payment',
            new_name='payment1',
        ),
        migrations.AddField(
            model_name='person',
            name='amount2',
            field=models.CharField(default='Default amount', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='amount3',
            field=models.CharField(default='Default amount', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='loan2',
            field=models.CharField(default='Default loan', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='loan3',
            field=models.CharField(default='Default loan', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='payment2',
            field=models.CharField(default='Default payment', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='payment3',
            field=models.CharField(default='Default payment', max_length=100),
        ),
    ]
