# Generated by Django 5.0.3 on 2024-05-23 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_amount_person_amount1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='eduform1',
            new_name='Education',
        ),
        migrations.RenameModel(
            old_name='Person',
            new_name='Financial',
        ),
        migrations.RenameModel(
            old_name='personform1',
            new_name='Personal',
        ),
        migrations.RenameModel(
            old_name='numbers',
            new_name='Professional',
        ),
    ]
