# Generated by Django 5.0.3 on 2024-05-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_education_passoutyear1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='bp',
            field=models.CharField(max_length=10),
        ),
    ]
