# Generated by Django 5.0.3 on 2024-06-11 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_medical_allergy_alter_medical_asthma_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
